//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_nsi
    {
        public int id_agr { get; set; }
        public int kodKs { get; set; }
        public int kodKc { get; set; }
        public int kodAgr { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    }
}
