//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASDU_ESG_1_old
    {
        public string Session { get; set; }
        public string MsgType { get; set; }
        public System.DateTime DTS { get; set; }
        public Nullable<int> CommonCount { get; set; }
        public Nullable<int> PeredDost { get; set; }
        public Nullable<int> PeredNeDost { get; set; }
        public Nullable<int> Pustoe { get; set; }
        public Nullable<int> NeChislo { get; set; }
        public Nullable<int> NeVhodVInt { get; set; }
        public Nullable<int> OtsutPriv { get; set; }
    }
}
