//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsoduStatistic
    {
        public int id { get; set; }
        public int kodLpu { get; set; }
        public int handEnterCount { get; set; }
        public int handEnterAutoCount { get; set; }
        public int goodQualityCount { get; set; }
        public int tagCount { get; set; }
        public System.DateTime createDt { get; set; }
        public int repairCount { get; set; }
        public Nullable<int> bedQualityCount { get; set; }
    }
}
