//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsoduDataLPU
    {
        public int id { get; set; }
        public System.DateTime dt { get; set; }
        public string TagName { get; set; }
        public short kodLPU { get; set; }
        public int OPCQuality { get; set; }
        public Nullable<decimal> TagValue { get; set; }
    }
}
