//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IasInfo
    {
        public string TagName { get; set; }
        public string LongDesc { get; set; }
        public string ShortDesc { get; set; }
        public string InputSystem { get; set; }
        public string InputSource { get; set; }
        public string EngUnits { get; set; }
        public string IDObj { get; set; }
        public string IDType { get; set; }
        public string SAUType { get; set; }
        public Nullable<int> IDSauType { get; set; }
    }
}
