//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval_nsi
    {
        public int id_interval { get; set; }
        public string title { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
        public Nullable<int> sort_order { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
    }
}
