//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KC_nsi
    {
        public int id_kc { get; set; }
        public int id_ks { get; set; }
        public int kodKs { get; set; }
        public int kodKc { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
        public virtual KS_nsi KS_nsi { get; set; }
    }
}
