//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KS_nsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KS_nsi()
        {
            this.KC_nsi = new HashSet<KC_nsi>();
        }
    
        public int id_ks { get; set; }
        public Nullable<int> kodks { get; set; }
        public string title { get; set; }
        public string stitle { get; set; }
        public string ks_name { get; set; }
        public Nullable<int> id_lpu { get; set; }
        public string ks_lpu_name { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KC_nsi> KC_nsi { get; set; }
        public virtual LPU_nsi LPU_nsi { get; set; }
    }
}
