//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPU_nsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LPU_nsi()
        {
            this.KS_nsi = new HashSet<KS_nsi>();
        }
    
        public int id_lpu { get; set; }
        public int kodlpu { get; set; }
        public Nullable<int> kodlpu_old { get; set; }
        public string title { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
        public Nullable<int> kodlpu_union { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KS_nsi> KS_nsi { get; set; }
    }
}
