//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telemehanica_levels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telemehanica_levels()
        {
            this.IusTags = new HashSet<IusTags>();
        }
    
        public int id_telemehanica_levels { get; set; }
        public string title { get; set; }
        public string template { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IusTags> IusTags { get; set; }
    }
}
