//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telemehanica_types
    {
        public int id_telemehanica_types { get; set; }
        public string title { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
    }
}
