//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Events_history = new HashSet<Events_history>();
        }
    
        public int id_user { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public bool is_active { get; set; }
        public System.DateTime last_login { get; set; }
        public Nullable<int> id_deleted_nsi_obj { get; set; }
    
        public virtual Deleted_nsi_obj Deleted_nsi_obj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events_history> Events_history { get; set; }
    }
}
