//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_paramASDU_ESG
    {
        public string LPUTitle { get; set; }
        public short kodLPU { get; set; }
        public System.DateTime DTS { get; set; }
        public string SessionTitle { get; set; }
        public string MsgType { get; set; }
        public string FulParamName { get; set; }
        public string TagName { get; set; }
        public string ParamId { get; set; }
        public string ParamValue { get; set; }
        public int ErrCategoryId { get; set; }
    }
}
