//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WEB_REPORTSContext : DbContext
    {
        public WEB_REPORTSContext()
            : base("name=WEB_REPORTSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGR_nsi> AGR_nsi { get; set; }
        public virtual DbSet<AsoduDataKc> AsoduDataKc { get; set; }
        public virtual DbSet<AsoduDataLPU> AsoduDataLPU { get; set; }
        public virtual DbSet<AsoduManualTags> AsoduManualTags { get; set; }
        public virtual DbSet<AsoduStatistic> AsoduStatistic { get; set; }
        public virtual DbSet<AsoduStatisticNew> AsoduStatisticNew { get; set; }
        public virtual DbSet<Deleted_nsi_obj> Deleted_nsi_obj { get; set; }
        public virtual DbSet<Events_history> Events_history { get; set; }
        public virtual DbSet<IasInfo> IasInfo { get; set; }
        public virtual DbSet<Interval_nsi> Interval_nsi { get; set; }
        public virtual DbSet<IusTags> IusTags { get; set; }
        public virtual DbSet<KC_nsi> KC_nsi { get; set; }
        public virtual DbSet<KS_nsi> KS_nsi { get; set; }
        public virtual DbSet<LPU_nsi> LPU_nsi { get; set; }
        public virtual DbSet<Quality_types> Quality_types { get; set; }
        public virtual DbSet<SauType_nsi> SauType_nsi { get; set; }
        public virtual DbSet<Telemehanica_levels> Telemehanica_levels { get; set; }
        public virtual DbSet<Telemehanica_types> Telemehanica_types { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ZAR_NSI> ZAR_NSI { get; set; }
        public virtual DbSet<ASDU_ESG_1> ASDU_ESG_1 { get; set; }
        public virtual DbSet<ASDU_ESG_1_old> ASDU_ESG_1_old { get; set; }
        public virtual DbSet<v_ASDU_ESG_LPU> v_ASDU_ESG_LPU { get; set; }
        public virtual DbSet<v_paramASDU_ESG> v_paramASDU_ESG { get; set; }
        public virtual DbSet<v_SessionList> v_SessionList { get; set; }
        public virtual DbSet<v_SessionList_old> v_SessionList_old { get; set; }
        public virtual DbSet<Справочник_IUSTags> Справочник_IUSTags { get; set; }
        public virtual DbSet<ZAR_STATES_ALL> ZAR_STATES_ALL { get; set; }
        public virtual DbSet<ZAR_NSI_WEB> ZAR_NSI_WEB { get; set; }
    
        public virtual int get_Asodu_data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Asodu_data");
        }
    
        public virtual int get_Asodu_dataKC_modern(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Asodu_dataKC_modern", dtbeginParameter, dtendParameter);
        }
    
        public virtual int get_Asodu_dataLPU_modern(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Asodu_dataLPU_modern", dtbeginParameter, dtendParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsKC_Result> get_Asodu_intervalsKC(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodKS, Nullable<short> kodKC, Nullable<int> minLen, Nullable<int> maxLen)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodKSParameter = kodKS.HasValue ?
                new ObjectParameter("kodKS", kodKS) :
                new ObjectParameter("kodKS", typeof(short));
    
            var kodKCParameter = kodKC.HasValue ?
                new ObjectParameter("kodKC", kodKC) :
                new ObjectParameter("kodKC", typeof(short));
    
            var minLenParameter = minLen.HasValue ?
                new ObjectParameter("minLen", minLen) :
                new ObjectParameter("minLen", typeof(int));
    
            var maxLenParameter = maxLen.HasValue ?
                new ObjectParameter("maxLen", maxLen) :
                new ObjectParameter("maxLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsKC_Result>("get_Asodu_intervalsKC", dtbeginParameter, dtendParameter, kodKSParameter, kodKCParameter, minLenParameter, maxLenParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsKC_2_Result> get_Asodu_intervalsKC_2(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodKS, Nullable<short> kodKC, Nullable<short> lenFilt)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodKSParameter = kodKS.HasValue ?
                new ObjectParameter("kodKS", kodKS) :
                new ObjectParameter("kodKS", typeof(short));
    
            var kodKCParameter = kodKC.HasValue ?
                new ObjectParameter("kodKC", kodKC) :
                new ObjectParameter("kodKC", typeof(short));
    
            var lenFiltParameter = lenFilt.HasValue ?
                new ObjectParameter("lenFilt", lenFilt) :
                new ObjectParameter("lenFilt", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsKC_2_Result>("get_Asodu_intervalsKC_2", dtbeginParameter, dtendParameter, kodKSParameter, kodKCParameter, lenFiltParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsLPU_Result> get_Asodu_intervalsLPU(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodLPU, Nullable<int> minLen, Nullable<int> maxLen)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodLPUParameter = kodLPU.HasValue ?
                new ObjectParameter("kodLPU", kodLPU) :
                new ObjectParameter("kodLPU", typeof(short));
    
            var minLenParameter = minLen.HasValue ?
                new ObjectParameter("minLen", minLen) :
                new ObjectParameter("minLen", typeof(int));
    
            var maxLenParameter = maxLen.HasValue ?
                new ObjectParameter("maxLen", maxLen) :
                new ObjectParameter("maxLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsLPU_Result>("get_Asodu_intervalsLPU", dtbeginParameter, dtendParameter, kodLPUParameter, minLenParameter, maxLenParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsLPU_2_Result> get_Asodu_intervalsLPU_2(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodLPU, Nullable<short> lenFilt)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodLPUParameter = kodLPU.HasValue ?
                new ObjectParameter("kodLPU", kodLPU) :
                new ObjectParameter("kodLPU", typeof(short));
    
            var lenFiltParameter = lenFilt.HasValue ?
                new ObjectParameter("lenFilt", lenFilt) :
                new ObjectParameter("lenFilt", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsLPU_2_Result>("get_Asodu_intervalsLPU_2", dtbeginParameter, dtendParameter, kodLPUParameter, lenFiltParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsManualTags_Result> get_Asodu_intervalsManualTags(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodKS, Nullable<short> kodKC, string tagType, Nullable<int> minLen, Nullable<int> maxLen)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodKSParameter = kodKS.HasValue ?
                new ObjectParameter("kodKS", kodKS) :
                new ObjectParameter("kodKS", typeof(short));
    
            var kodKCParameter = kodKC.HasValue ?
                new ObjectParameter("kodKC", kodKC) :
                new ObjectParameter("kodKC", typeof(short));
    
            var tagTypeParameter = tagType != null ?
                new ObjectParameter("tagType", tagType) :
                new ObjectParameter("tagType", typeof(string));
    
            var minLenParameter = minLen.HasValue ?
                new ObjectParameter("minLen", minLen) :
                new ObjectParameter("minLen", typeof(int));
    
            var maxLenParameter = maxLen.HasValue ?
                new ObjectParameter("maxLen", maxLen) :
                new ObjectParameter("maxLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsManualTags_Result>("get_Asodu_intervalsManualTags", dtbeginParameter, dtendParameter, kodKSParameter, kodKCParameter, tagTypeParameter, minLenParameter, maxLenParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsManualTags_0ld_Result> get_Asodu_intervalsManualTags_0ld(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodKS, Nullable<short> kodKC, string tagType, Nullable<int> minLen, Nullable<int> maxLen)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodKSParameter = kodKS.HasValue ?
                new ObjectParameter("kodKS", kodKS) :
                new ObjectParameter("kodKS", typeof(short));
    
            var kodKCParameter = kodKC.HasValue ?
                new ObjectParameter("kodKC", kodKC) :
                new ObjectParameter("kodKC", typeof(short));
    
            var tagTypeParameter = tagType != null ?
                new ObjectParameter("tagType", tagType) :
                new ObjectParameter("tagType", typeof(string));
    
            var minLenParameter = minLen.HasValue ?
                new ObjectParameter("minLen", minLen) :
                new ObjectParameter("minLen", typeof(int));
    
            var maxLenParameter = maxLen.HasValue ?
                new ObjectParameter("maxLen", maxLen) :
                new ObjectParameter("maxLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsManualTags_0ld_Result>("get_Asodu_intervalsManualTags_0ld", dtbeginParameter, dtendParameter, kodKSParameter, kodKCParameter, tagTypeParameter, minLenParameter, maxLenParameter);
        }
    
        public virtual ObjectResult<get_Asodu_intervalsManualTags1_Result> get_Asodu_intervalsManualTags1(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend, Nullable<short> kodKS, Nullable<short> kodKC, Nullable<int> minLen, Nullable<int> maxLen)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            var kodKSParameter = kodKS.HasValue ?
                new ObjectParameter("kodKS", kodKS) :
                new ObjectParameter("kodKS", typeof(short));
    
            var kodKCParameter = kodKC.HasValue ?
                new ObjectParameter("kodKC", kodKC) :
                new ObjectParameter("kodKC", typeof(short));
    
            var minLenParameter = minLen.HasValue ?
                new ObjectParameter("minLen", minLen) :
                new ObjectParameter("minLen", typeof(int));
    
            var maxLenParameter = maxLen.HasValue ?
                new ObjectParameter("maxLen", maxLen) :
                new ObjectParameter("maxLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Asodu_intervalsManualTags1_Result>("get_Asodu_intervalsManualTags1", dtbeginParameter, dtendParameter, kodKSParameter, kodKCParameter, minLenParameter, maxLenParameter);
        }
    
        public virtual int get_Asodu_ManualTags(Nullable<System.DateTime> dtbegin, Nullable<System.DateTime> dtend)
        {
            var dtbeginParameter = dtbegin.HasValue ?
                new ObjectParameter("dtbegin", dtbegin) :
                new ObjectParameter("dtbegin", typeof(System.DateTime));
    
            var dtendParameter = dtend.HasValue ?
                new ObjectParameter("dtend", dtend) :
                new ObjectParameter("dtend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Asodu_ManualTags", dtbeginParameter, dtendParameter);
        }
    
        public virtual int get_Asodu_StatisticData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Asodu_StatisticData");
        }
    
        public virtual ObjectResult<hp_GetAsduEsg1_Result> hp_GetAsduEsg1(string sesion, Nullable<System.DateTime> dt)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("Dt", dt) :
                new ObjectParameter("Dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetAsduEsg1_Result>("hp_GetAsduEsg1", sesionParameter, dtParameter);
        }
    
        public virtual ObjectResult<hp_GetAsduEsg1Period_Result> hp_GetAsduEsg1Period(string sesion, Nullable<System.DateTime> dt, Nullable<System.DateTime> endDt)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("Dt", dt) :
                new ObjectParameter("Dt", typeof(System.DateTime));
    
            var endDtParameter = endDt.HasValue ?
                new ObjectParameter("EndDt", endDt) :
                new ObjectParameter("EndDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetAsduEsg1Period_Result>("hp_GetAsduEsg1Period", sesionParameter, dtParameter, endDtParameter);
        }
    
        public virtual ObjectResult<hp_GetAsduEsgLPU_Result> hp_GetAsduEsgLPU(string sesion, Nullable<System.DateTime> dt)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("Dt", dt) :
                new ObjectParameter("Dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetAsduEsgLPU_Result>("hp_GetAsduEsgLPU", sesionParameter, dtParameter);
        }
    
        public virtual ObjectResult<hp_GetAsduEsgLPUPeriod_Result> hp_GetAsduEsgLPUPeriod(string sesion, Nullable<System.DateTime> dt, Nullable<System.DateTime> endDt)
        {
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("Dt", dt) :
                new ObjectParameter("Dt", typeof(System.DateTime));
    
            var endDtParameter = endDt.HasValue ?
                new ObjectParameter("EndDt", endDt) :
                new ObjectParameter("EndDt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetAsduEsgLPUPeriod_Result>("hp_GetAsduEsgLPUPeriod", sesionParameter, dtParameter, endDtParameter);
        }
    
        public virtual ObjectResult<hp_GetDoGroupKcList_Result> hp_GetDoGroupKcList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetDoGroupKcList_Result>("hp_GetDoGroupKcList");
        }
    
        public virtual int hp_GetHandEnterData(Nullable<int> kodlpu, Nullable<int> kodks, string dt)
        {
            var kodlpuParameter = kodlpu.HasValue ?
                new ObjectParameter("kodlpu", kodlpu) :
                new ObjectParameter("kodlpu", typeof(int));
    
            var kodksParameter = kodks.HasValue ?
                new ObjectParameter("kodks", kodks) :
                new ObjectParameter("kodks", typeof(int));
    
            var dtParameter = dt != null ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetHandEnterData", kodlpuParameter, kodksParameter, dtParameter);
        }
    
        public virtual int hp_GetLiveStatisticData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetLiveStatisticData");
        }
    
        public virtual int hp_GetLiveStatisticData_History()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetLiveStatisticData_History");
        }
    
        public virtual int hp_GetLiveStatisticData_Repair()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetLiveStatisticData_Repair");
        }
    
        public virtual int hp_GetLiveStatisticData_RepairNew(string objectString)
        {
            var objectStringParameter = objectString != null ?
                new ObjectParameter("objectString", objectString) :
                new ObjectParameter("objectString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetLiveStatisticData_RepairNew", objectStringParameter);
        }
    
        public virtual int hp_GetLiveTagList(Nullable<int> kodlpu, Nullable<int> qualitytypeId)
        {
            var kodlpuParameter = kodlpu.HasValue ?
                new ObjectParameter("kodlpu", kodlpu) :
                new ObjectParameter("kodlpu", typeof(int));
    
            var qualitytypeIdParameter = qualitytypeId.HasValue ?
                new ObjectParameter("qualitytypeId", qualitytypeId) :
                new ObjectParameter("qualitytypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetLiveTagList", kodlpuParameter, qualitytypeIdParameter);
        }
    
        public virtual ObjectResult<hp_GetObjTypeList_Result> hp_GetObjTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetObjTypeList_Result>("hp_GetObjTypeList");
        }
    
        public virtual ObjectResult<hp_GetParamAsduEsg_Result> hp_GetParamAsduEsg(string lputitle, Nullable<int> errCategoryId, string sesion, Nullable<System.DateTime> dt)
        {
            var lputitleParameter = lputitle != null ?
                new ObjectParameter("lputitle", lputitle) :
                new ObjectParameter("lputitle", typeof(string));
    
            var errCategoryIdParameter = errCategoryId.HasValue ?
                new ObjectParameter("ErrCategoryId", errCategoryId) :
                new ObjectParameter("ErrCategoryId", typeof(int));
    
            var sesionParameter = sesion != null ?
                new ObjectParameter("sesion", sesion) :
                new ObjectParameter("sesion", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("Dt", dt) :
                new ObjectParameter("Dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetParamAsduEsg_Result>("hp_GetParamAsduEsg", lputitleParameter, errCategoryIdParameter, sesionParameter, dtParameter);
        }
    
        public virtual ObjectResult<hp_GetPeriodChartData_Result> hp_GetPeriodChartData(Nullable<int> kodlpu, string startDt, string endDt)
        {
            var kodlpuParameter = kodlpu.HasValue ?
                new ObjectParameter("kodlpu", kodlpu) :
                new ObjectParameter("kodlpu", typeof(int));
    
            var startDtParameter = startDt != null ?
                new ObjectParameter("startDt", startDt) :
                new ObjectParameter("startDt", typeof(string));
    
            var endDtParameter = endDt != null ?
                new ObjectParameter("endDt", endDt) :
                new ObjectParameter("endDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetPeriodChartData_Result>("hp_GetPeriodChartData", kodlpuParameter, startDtParameter, endDtParameter);
        }
    
        public virtual ObjectResult<hp_GetPeriodStatisticData_Result> hp_GetPeriodStatisticData(string startDt, string endDt)
        {
            var startDtParameter = startDt != null ?
                new ObjectParameter("startDt", startDt) :
                new ObjectParameter("startDt", typeof(string));
    
            var endDtParameter = endDt != null ?
                new ObjectParameter("endDt", endDt) :
                new ObjectParameter("endDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetPeriodStatisticData_Result>("hp_GetPeriodStatisticData", startDtParameter, endDtParameter);
        }
    
        public virtual ObjectResult<hp_GetPeriodStatisticData_old_Result> hp_GetPeriodStatisticData_old(string startDt, string endDt)
        {
            var startDtParameter = startDt != null ?
                new ObjectParameter("startDt", startDt) :
                new ObjectParameter("startDt", typeof(string));
    
            var endDtParameter = endDt != null ?
                new ObjectParameter("endDt", endDt) :
                new ObjectParameter("endDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetPeriodStatisticData_old_Result>("hp_GetPeriodStatisticData_old", startDtParameter, endDtParameter);
        }
    
        public virtual int hp_GetPeriodTagList(Nullable<int> kodlpu, Nullable<int> qualitytypeId, string startDt, string endDt)
        {
            var kodlpuParameter = kodlpu.HasValue ?
                new ObjectParameter("kodlpu", kodlpu) :
                new ObjectParameter("kodlpu", typeof(int));
    
            var qualitytypeIdParameter = qualitytypeId.HasValue ?
                new ObjectParameter("qualitytypeId", qualitytypeId) :
                new ObjectParameter("qualitytypeId", typeof(int));
    
            var startDtParameter = startDt != null ?
                new ObjectParameter("startDt", startDt) :
                new ObjectParameter("startDt", typeof(string));
    
            var endDtParameter = endDt != null ?
                new ObjectParameter("endDt", endDt) :
                new ObjectParameter("endDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetPeriodTagList", kodlpuParameter, qualitytypeIdParameter, startDtParameter, endDtParameter);
        }
    
        public virtual ObjectResult<hp_GetTagTypeList_Result> hp_GetTagTypeList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetTagTypeList_Result>("hp_GetTagTypeList");
        }
    
        public virtual ObjectResult<string> hp_GetTelemehanica_SauKc(Nullable<int> kodLpu, Nullable<int> kodKs)
        {
            var kodLpuParameter = kodLpu.HasValue ?
                new ObjectParameter("kodLpu", kodLpu) :
                new ObjectParameter("kodLpu", typeof(int));
    
            var kodKsParameter = kodKs.HasValue ?
                new ObjectParameter("kodKs", kodKs) :
                new ObjectParameter("kodKs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("hp_GetTelemehanica_SauKc", kodLpuParameter, kodKsParameter);
        }
    
        public virtual ObjectResult<hp_GetTelemehanicaConnectSystemData_Result> hp_GetTelemehanicaConnectSystemData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetTelemehanicaConnectSystemData_Result>("hp_GetTelemehanicaConnectSystemData");
        }
    
        public virtual ObjectResult<hp_GetTelemehanicaConnectSystemGpaData_Result> hp_GetTelemehanicaConnectSystemGpaData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetTelemehanicaConnectSystemGpaData_Result>("hp_GetTelemehanicaConnectSystemGpaData");
        }
    
        public virtual ObjectResult<hp_GetTelemehanicaConnectSystemGpaDataByKod_Result> hp_GetTelemehanicaConnectSystemGpaDataByKod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetTelemehanicaConnectSystemGpaDataByKod_Result>("hp_GetTelemehanicaConnectSystemGpaDataByKod");
        }
    
        public virtual ObjectResult<hp_GetTelemehanicaConnectSystemKcData_Result> hp_GetTelemehanicaConnectSystemKcData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hp_GetTelemehanicaConnectSystemKcData_Result>("hp_GetTelemehanicaConnectSystemKcData");
        }
    
        public virtual int hp_GetTelemehanicaReportData(Nullable<int> lpu_id, Nullable<int> ks_id, Nullable<int> level_id, Nullable<int> telemehanicatype_id)
        {
            var lpu_idParameter = lpu_id.HasValue ?
                new ObjectParameter("lpu_id", lpu_id) :
                new ObjectParameter("lpu_id", typeof(int));
    
            var ks_idParameter = ks_id.HasValue ?
                new ObjectParameter("ks_id", ks_id) :
                new ObjectParameter("ks_id", typeof(int));
    
            var level_idParameter = level_id.HasValue ?
                new ObjectParameter("level_id", level_id) :
                new ObjectParameter("level_id", typeof(int));
    
            var telemehanicatype_idParameter = telemehanicatype_id.HasValue ?
                new ObjectParameter("telemehanicatype_id", telemehanicatype_id) :
                new ObjectParameter("telemehanicatype_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hp_GetTelemehanicaReportData", lpu_idParameter, ks_idParameter, level_idParameter, telemehanicatype_idParameter);
        }
    
        public virtual int rts_GetStatisticDataFromLpu(string startDt, string endDt, Nullable<short> kodLPU, Nullable<short> forBDRV2)
        {
            var startDtParameter = startDt != null ?
                new ObjectParameter("startDt", startDt) :
                new ObjectParameter("startDt", typeof(string));
    
            var endDtParameter = endDt != null ?
                new ObjectParameter("endDt", endDt) :
                new ObjectParameter("endDt", typeof(string));
    
            var kodLPUParameter = kodLPU.HasValue ?
                new ObjectParameter("kodLPU", kodLPU) :
                new ObjectParameter("kodLPU", typeof(short));
    
            var forBDRV2Parameter = forBDRV2.HasValue ?
                new ObjectParameter("forBDRV2", forBDRV2) :
                new ObjectParameter("forBDRV2", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rts_GetStatisticDataFromLpu", startDtParameter, endDtParameter, kodLPUParameter, forBDRV2Parameter);
        }
    }
}
