//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAR_STATES_ALL
    {
        public long id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string TagName { get; set; }
        public double Value { get; set; }
        public int Quality { get; set; }
    }
}
