//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAR_NSI_WEB
    {
        public int Id { get; set; }
        public string LPU_Name { get; set; }
        public string KP_Name { get; set; }
        public string kodZAR_SLTM { get; set; }
        public string kodZAR_SODU { get; set; }
        public string Tagname { get; set; }
        public string ShortZAR_Name { get; set; }
        public string Comment { get; set; }
        public string LongZAR_Name { get; set; }
    }
}
