//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_IUSTags
    {
        public string title { get; set; }
        public string ks_lpu_name { get; set; }
        public Nullable<int> kodKc { get; set; }
        public Nullable<int> kodAgr { get; set; }
        public string TagName { get; set; }
        public string LongDesc { get; set; }
        public string ShortDesc { get; set; }
        public string Algorithm { get; set; }
        public string InputSystem { get; set; }
        public string InputSource { get; set; }
    }
}
